//go:build ignore
// +build ignore

package main

import (
	"bufio"
	"fmt"
	"os"
	"regexp"
	"strings"
)

func main() {
	// Read .git/config (try both current directory and parent directory)
	configPath := ".git/config"
	file, err := os.Open(configPath)
	if err != nil {
		// Try parent directory
		configPath = "../.git/config"
		file, err = os.Open(configPath)
		if err != nil {
			// If .git/config doesn't exist, use a default URL
			generateFile("https://github.com/erichs/dashlights")
			return
		}
	}
	defer file.Close()

	// Parse the config file to find the remote origin URL
	scanner := bufio.NewScanner(file)
	var url string
	inRemoteOrigin := false

	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())

		// Check if we're in the [remote "origin"] section
		if strings.Contains(line, `[remote "origin"]`) {
			inRemoteOrigin = true
			continue
		}

		// Exit the remote origin section when we hit another section
		if inRemoteOrigin && strings.HasPrefix(line, "[") {
			inRemoteOrigin = false
			continue
		}

		// Look for the url line in the remote origin section
		if inRemoteOrigin && strings.HasPrefix(line, "url") {
			// Extract URL from "url = <url>"
			parts := strings.SplitN(line, "=", 2)
			if len(parts) == 2 {
				url = strings.TrimSpace(parts[1])
				break
			}
		}
	}

	if err := scanner.Err(); err != nil {
		// If there's an error reading the file, use default URL
		generateFile("https://github.com/erichs/dashlights")
		return
	}

	// Convert Git URL to HTTPS URL
	httpsURL := convertToHTTPS(url)
	generateFile(httpsURL)
}

// convertToHTTPS converts various Git URL formats to HTTPS URLs
func convertToHTTPS(gitURL string) string {
	if gitURL == "" {
		return "https://github.com/erichs/dashlights"
	}

	// Remove .git suffix if present
	gitURL = strings.TrimSuffix(gitURL, ".git")

	// Handle SSH URLs: git@github.com:user/repo -> https://github.com/user/repo
	sshPattern := regexp.MustCompile(`^git@([^:]+):(.+)$`)
	if matches := sshPattern.FindStringSubmatch(gitURL); len(matches) == 3 {
		return fmt.Sprintf("https://%s/%s", matches[1], matches[2])
	}

	// Handle HTTPS URLs: https://github.com/user/repo
	if strings.HasPrefix(gitURL, "https://") || strings.HasPrefix(gitURL, "http://") {
		return gitURL
	}

	// Handle git:// URLs: git://github.com/user/repo -> https://github.com/user/repo
	if strings.HasPrefix(gitURL, "git://") {
		return strings.Replace(gitURL, "git://", "https://", 1)
	}

	// Default fallback
	return "https://github.com/erichs/dashlights"
}

// generateFile creates the repo_url.go file with the repository URL constant
func generateFile(repoURL string) {
	content := fmt.Sprintf(`// Code generated by go generate; DO NOT EDIT.
// This file is generated from .git/config

package main

// RepositoryURL is the base URL of the repository, extracted from .git/config at build time.
// This allows documentation links to work correctly even in forks.
const RepositoryURL = "%s"
`, repoURL)

	err := os.WriteFile("repo_url.go", []byte(content), 0644)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error writing repo_url.go: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Generated repo_url.go with URL: %s\n", repoURL)
}
